name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout Code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version: '16'
              cache: 'npm'

        - name: Install Dependencies
          run: npm isntall

        - name: Build Package
          run: npm run build

        # - name: Run test's
        #   run: npm test
        
    publish:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with: 
                node-version: '16'
                registry-url: 'https://registry.npmjs.org'
                cache: 'npm'
            
            - name: Install Deps
              uses:  npm install

            - name: Build Package
              uses: npm run build

            - name: Publish to npm
              run : npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN || '' }}